# This workflow is intended to build the C# .Net based module named T3000Controls

name: CI

# On master make sure both push and a pull request builds this action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: checkout
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: cmake
      - run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ../T3000Controls

      - name: cmake-build
        run: |
          echo CMake configuration successful. Going for build...
          cmake --build .
